### ISSUE TITLE
left and right panels

### ISSUE THREAD

**Issue by Zoophobus** [Pan6ora/ab-plugin-Notebook#1]
Hi Pan6ora,

I've not been over here much, but I'll probably be coming here more. I was, originally, hoping to persuade you that it would be best to fix the plugins to only appear on the right panel of the AB! (Currently the notebooks appear on both the right and left panels, which could be improved.) However I figured you went for providing the contributors with both options, something I find hard to disagree with.

So I just wanted to ask if you'd mind changing the notebooks to just appear on the right panel?

Thanks for all of your hard work!

**Comment by Pan6ora** [comment]
Hi @Zoophobus,

> However I figured you went for providing the contributors with both options

You're right. A plugin can only add one tab on each side but it doesn't have to.

> So I just wanted to ask if you'd mind changing the notebooks to just appear on the right panel?

I completely agree. I originally planned to use it, but at the end not and forgot to remove it.  This is fixed in `v0.2.5`.
